config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact',  to: 'pages#contact'
  get 'retreat',  to: 'pages#retreat'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
     <%= @copyright %>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Mark Nelson</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %>
  <p><a href="#">Back to top</a></p>
</footer>

app/views/shared/_blog_masthead.html.erb
 <div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Blog for Web application development.</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to 'Topics', topics_path if logged_in?(:site_admin) %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Web application developer using Ruby on Rails.</p>
  </div>
  <div>
    <p><%= source_helper("alert alert-info") %></p>
  </div>
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @sidebar_topics.each do |topic| %>
      <%= link_to topic.title, topic_path(topic) %><br/>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Links</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"<%= fa_icon "github" %></a></li>
      <li><a href="#"<%= fa_icon "instagram" %></a></li>
      <li><a href="#"<%= fa_icon "twitter" %></a></li>
      <li><a href="#"<%= fa_icon "facebook" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    <%= link_to "View all Portfolio Items", portfolios_path %> |
    <a href="#">Back to top</a></p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
<div class="container">
  <h1 class="jumbotron-heading">Album example</h1>
  <p class="lead text-muted">Portfolio of applications developed using Runy on Rails.</p>
  <p>
    <%= link_to 'Find out more about me', about_me_path, class: 'btn btn-primary' %>
    <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
  </p>
  <%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>
</div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Web applications developed using Ruby on Rails.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Mark X</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>